#!/usr/bin/env node

const queries = require('../queries.json');

let content = `# Active Media Queries

Finds a list of all active media queries supported by your browser. Will show you exactly what matches, plus it will respond to changes.

[See it live! 🚀](https://fidian.github.io/active-media-queries/)

## What's detected

`;

for (const query of queries) {
    content += `* [${query.name}](${query.url}) - ${query.description}\n`;
}

content += `
## Need more?

The repository contains a file called \`queries.json\` that drives everything. Update it and use \`make\` to build the HTML and the README.`;

console.log(content);
